## Load Data
### Download data from Kaggle
- 0801 - 0821: download from code
- 0822 - 0831: download manually (dont know why.....)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
from kagglehub import KaggleDatasetAdapter
from datetime import datetime

In [44]:
#!pip install kaggle
#!pip install kagglehub
#!pip install kagglehub[pandas-datasets]

In [12]:
# set date range
start_date = datetime(2024, 8, 1)
end_date = datetime(2024, 8, 21)

# Load data
df_gaming = []
df_movies = []
df_music = []
files = ["gaming", "movies", "music"]

for cat in files:
    for date in pd.date_range(start_date, end_date):
        file_path = f"{cat}/{cat}_{date.strftime('%Y%m%d')}.csv"
        df_single = kagglehub.load_dataset(
            KaggleDatasetAdapter.PANDAS,
            "pyuser11/youtube-trending-videos-updated-daily",
            file_path
        )
        eval(f"df_{cat}").append(df_single)

# combine all df
df_gaming_0821 = pd.concat(df_gaming, ignore_index=True)
df_movies_0821 = pd.concat(df_movies, ignore_index=True)
df_music_0821 = pd.concat(df_music, ignore_index=True)

C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(
C:\Users\morga\AppData\Local\Temp\ipykernel_13316\2139100597.py:14: DeprecationWarning: load_dataset is deprecated and will be removed in future version.
  df_single = kagglehub.load_dataset(

KaggleApiHTTPError: 404 Client Error.

Resource not found at URL: https://www.kaggle.com/datasets/pyuser11/youtube-trending-videos-updated-daily
Please make sure you specified the correct resource identifiers.

In [33]:
#df_trial = pd.read_csv("data/gaming/gaming_20240822.csv")

# from 0822 - 0831
start_date = datetime(2024, 8, 22)
end_date = datetime(2024, 8, 31)

# save dfs into their own category
df_dict = {
    "gaming":[], 
    "movies":[],
    "music":[]
}

files = ["gaming", "movies", "music"]
for name in files:
    for date in pd.date_range(start_date, end_date):
        link = f"data/{name}/{name}_{date.strftime('%Y%m%d')}.csv"
        df_single = pd.read_csv(link)
        df_dict[name].append(df_single)
#print(df_dict)

# combine all df
df_gaming_0831 = pd.concat(df_dict["gaming"], ignore_index=True)
df_movies_0831 = pd.concat(df_dict["movies"], ignore_index=True)
df_music_0831 = pd.concat(df_dict["music"], ignore_index=True)

In [34]:
# combine 0821 and 0831 data
df_gaming = pd.concat([df_gaming_0821, df_gaming_0831], ignore_index=True)
df_movies = pd.concat([df_movies_0821, df_movies_0831], ignore_index=True)
df_music = pd.concat([df_music_0821, df_music_0831], ignore_index=True)

In [35]:
# check length
print(len(df_gaming) == len(df_gaming_0821)+len(df_gaming_0831))
print(len(df_movies) == len(df_movies_0821)+len(df_movies_0831))
print(len(df_music) == len(df_music_0821)+len(df_music_0831))

True
True
True

---

## Cleaning
### Gaming Dataframe

In [47]:
df_gaming.head()

,title,description,publishedDate,publishedText,videoId,videoUrl,channelName,channelId,channelUrl,thumbnails,views,viewsText,duration,durationText,verified,creatorOnRise,isShort
0,It's Clash Anime Season! Happy 12th Clashivers...,Join us in celebrating our 12th Clashiversary ...,2024-08-01T18:57:43.567Z,12 hours ago,aE10HERgL-4,https://youtube.com/watch?v=aE10HERgL-4,Clash of Clans,UCD1Em4q90ZUK2R5HKesszJg,https://youtube.com/@ClashOfClans,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",3014088,"3,014,088 views",35,0:35,True,False,False
1,Brawl Stars Animation: PAINT BRAWL STARTS NOW!,🫧 WE'RE BRAWLING IN THE DEEP! 🫧\n\n🎨 The new P...,2024-08-01T19:03:43.567Z,11 hours ago,RJw3Y-3EBFo,https://youtube.com/watch?v=RJw3Y-3EBFo,Brawl Stars,UCooVYzDxdwTtGYAkcPmOgOw,https://youtube.com/@BrawlStars,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",3165597,"3,165,597 views",52,0:52,True,False,False
2,NBA 2K25 | Official Gameplay Trailer,Pre-order now! ⬇️\nhttps://2kgam.es/3YtiOwC\n\...,2024-08-01T19:39:43.567Z,5 hours ago,qx0A921z8mA,https://youtube.com/watch?v=qx0A921z8mA,NBA 2K,UCYAJjqIukwm4r3GHEpJDhVw,https://youtube.com/@nba2k,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",70549,"70,549 views",118,1:58,True,False,False
3,Relentlessly Hunting Down My Friends That Are ...,Welcome back to Kill It With Fire 2 the game w...,2024-08-01T17:57:43.567Z,22 hours ago,jexy_g3l8tc,https://youtube.com/watch?v=jexy_g3l8tc,SMii7Y,UCzXwjTI6c6mVn6oui_p6oiw,https://youtube.com/@SMii7Y,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",1057349,"1,057,349 views",1272,21:12,True,False,False
4,WE'RE SO GOOD... | Chained Together - Part 5,We're so good at video games! Especially when ...,2024-08-01T17:51:43.567Z,23 hours ago,AmF6xoVAVI8,https://youtube.com/watch?v=AmF6xoVAVI8,Markiplier,UC7_YxT-KID8kRbqZo7MyscQ,https://youtube.com/@markiplier,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",681574,"681,574 views",1740,29:00,True,False,False

In [54]:
# structure
print(df_gaming.columns)
print(df_gaming.shape)

Index(['title', 'description', 'publishedDate', 'publishedText', 'videoId',
       'videoUrl', 'channelName', 'channelId', 'channelUrl', 'thumbnails',
       'views', 'viewsText', 'duration', 'durationText', 'verified',
       'creatorOnRise', 'isShort'],
      dtype='object')
(1550, 17)

In [76]:
# information
print(df_gaming.info())
print(df_gaming.describe())

# missing value
print(df_gaming.isna().sum())

# duplicate value
df_gaming.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1550 entries, 0 to 1549
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          1550 non-null   object
 1   description    1546 non-null   object
 2   publishedDate  1550 non-null   object
 3   publishedText  1550 non-null   object
 4   videoId        1550 non-null   object
 5   videoUrl       1550 non-null   object
 6   channelName    1550 non-null   object
 7   channelId      1550 non-null   object
 8   channelUrl     1550 non-null   object
 9   thumbnails     1550 non-null   object
 10  views          1550 non-null   int64
 11  viewsText      1550 non-null   object
 12  duration       1550 non-null   int64
 13  durationText   1550 non-null   object
 14  verified       1550 non-null   bool
 15  creatorOnRise  1550 non-null   bool
 16  isShort        1550 non-null   bool
dtypes: bool(3), int64(2), object(12)
memory usage: 174.2+ KB
None
              views      duration
count  1.550000e+03   1550.000000
mean   5.975984e+05   3573.383226
std    1.145748e+06   5930.620690
min    1.234000e+04     10.000000
25%    1.884875e+05    870.750000
50%    3.183535e+05   1558.500000
75%    6.133018e+05   3141.500000
max    1.707681e+07  42900.000000
title            0
description      4
publishedDate    0
publishedText    0
videoId          0
videoUrl         0
channelName      0
channelId        0
channelUrl       0
thumbnails       0
views            0
viewsText        0
duration         0
durationText     0
verified         0
creatorOnRise    0
isShort          0
dtype: int64

0

In [83]:
# view 4 missing description
mask = df_gaming["description"].isna()
df_gaming[mask]

,title,description,publishedDate,publishedText,videoId,videoUrl,channelName,channelId,channelUrl,thumbnails,views,viewsText,duration,durationText,verified,creatorOnRise,isShort
637,Stream ENDS IF I lose Madden 25,NaN,2024-08-13T18:38:50.846Z,Streamed 15 hours ago,5RT-xjK6co8,https://youtube.com/watch?v=5RT-xjK6co8,akaElectro,UClaQTfyXUl2CR1HYx0uVnRQ,https://youtube.com/@akaElectro,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",149511,"149,511 views",19522,5:25:22,False,False,False
1062,Hold grandpa back,NaN,2024-08-22T19:51:43.001Z,3 hours ago,pBkz5ccZxoU,https://youtube.com/watch?v=pBkz5ccZxoU,Habitual Linecrosser,UC6ysC3YUZbjScBKZlNLrmtQ,https://youtube.com/@habitual_linecrosser,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",79615,"79,615 views",160,2:40,True,False,False
1138,Hold grandpa back,NaN,2024-08-23T17:45:06.386Z,1 day ago,pBkz5ccZxoU,https://youtube.com/watch?v=pBkz5ccZxoU,Habitual Linecrosser,UC6ysC3YUZbjScBKZlNLrmtQ,https://youtube.com/@habitual_linecrosser,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",279826,"279,826 views",160,2:40,True,False,False
1488,the winged hussars have returned,NaN,2024-08-30T17:46:08.868Z,1 day ago,dRuJM6fakMg,https://youtube.com/watch?v=dRuJM6fakMg,Habitual Linecrosser,UC6ysC3YUZbjScBKZlNLrmtQ,https://youtube.com/@habitual_linecrosser,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",267320,"267,320 views",188,3:08,True,False,False

In [91]:
# save as csv
#df_gaming.to_csv("data/gaming.csv", index=False)

### Movies Dataframe

In [72]:
df_movies.head()

,title,description,publishedDate,publishedText,videoId,videoUrl,channelName,channelId,channelUrl,thumbnails,views,viewsText,duration,durationText,verified,creatorOnRise,isShort
0,Joker: Folie À Deux | Official Trailer,"When you’re smiling, the whole world smiles wi...",2024-07-31T22:33:43.999Z,9 days ago,_OKAwz2MsJs,https://youtube.com/watch?v=_OKAwz2MsJs,Warner Bros. Pictures,UCjmJDM5pRKbUlVIzDYYWb6g,https://youtube.com/@WarnerBrosPictures,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",23057474,"23,057,474 views",171,2:51,True,False,False
1,Captain America: Brave New World | Official Te...,Enter a brave new world.\n\nMarvel Studios' #C...,2024-07-31T10:33:43.999Z,2 weeks ago,O_A8HdCDaWM,https://youtube.com/watch?v=O_A8HdCDaWM,Marvel Entertainment,UCvC4D8onUfXzvjTOM-dBfEA,https://youtube.com/@marvel,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",18605168,"18,605,168 views",109,1:49,True,False,False
2,Deadpool & Wolverine | Final Trailer,This isn’t the movie you think it is. #Deadpoo...,2024-07-31T12:57:43.999Z,13 days ago,laNA2HgwYXU,https://youtube.com/watch?v=laNA2HgwYXU,Ryan Reynolds,UCA3-nIYWu4PTWkb6NwhEpzg,https://youtube.com/@VancityReynolds,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",10406325,"10,406,325 views",122,2:02,True,False,False
3,Gladiator II | Official Trailer (2024 Movie) -...,"From director Ridley Scott, watch the new Offi...",2024-07-30T17:45:43.999Z,3 weeks ago,4rgYUipGJNo,https://youtube.com/watch?v=4rgYUipGJNo,Paramount Pictures,UCF9imwPMSGz4Vq1NiTWCC7g,https://youtube.com/@paramountpictures,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",16402050,"16,402,050 views",190,3:10,True,False,False
4,A COMPLETE UNKNOWN | Official Teaser | Searchl...,Timothée Chalamet is Bob Dylan in A COMPLETE U...,2024-08-01T00:57:43.999Z,8 days ago,TcNNteP22gQ,https://youtube.com/watch?v=TcNNteP22gQ,SearchlightPictures,UCor9rW6PgxSQ9vUPWQdnaYQ,https://youtube.com/@searchlightpictures,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",3425568,"3,425,568 views",113,1:53,True,False,False

In [77]:
# structure
print(df_movies.columns)
print(df_movies.shape)

Index(['title', 'description', 'publishedDate', 'publishedText', 'videoId',
       'videoUrl', 'channelName', 'channelId', 'channelUrl', 'thumbnails',
       'views', 'viewsText', 'duration', 'durationText', 'verified',
       'creatorOnRise', 'isShort'],
      dtype='object')
(930, 17)

In [80]:
# information
print(df_movies.info())
print(df_movies.describe())

# missing value
print(df_movies.isna().sum())

# duplicate value
df_movies.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          930 non-null    object
 1   description    930 non-null    object
 2   publishedDate  930 non-null    object
 3   publishedText  930 non-null    object
 4   videoId        930 non-null    object
 5   videoUrl       930 non-null    object
 6   channelName    930 non-null    object
 7   channelId      930 non-null    object
 8   channelUrl     930 non-null    object
 9   thumbnails     930 non-null    object
 10  views          930 non-null    int64
 11  viewsText      930 non-null    object
 12  duration       930 non-null    int64
 13  durationText   930 non-null    object
 14  verified       930 non-null    bool
 15  creatorOnRise  930 non-null    bool
 16  isShort        930 non-null    bool
dtypes: bool(3), int64(2), object(12)
memory usage: 104.6+ KB
None
              views     duration
count  9.300000e+02   930.000000
mean   5.944953e+06   295.432258
std    9.058660e+06   418.304513
min    3.378800e+04    23.000000
25%    5.874420e+05   102.000000
50%    1.627145e+06   150.000000
75%    6.461906e+06   219.000000
max    4.705197e+07  3092.000000
title            0
description      0
publishedDate    0
publishedText    0
videoId          0
videoUrl         0
channelName      0
channelId        0
channelUrl       0
thumbnails       0
views            0
viewsText        0
duration         0
durationText     0
verified         0
creatorOnRise    0
isShort          0
dtype: int64

0

In [90]:
# save as csv
#df_movies.to_csv("data/movies.csv", index=False)

### Music Dataframe

In [79]:
df_music.head()

,title,description,publishedDate,publishedText,videoId,videoUrl,channelName,channelId,channelUrl,thumbnails,views,viewsText,duration,durationText,verified,creatorOnRise,isShort
0,mgk & Jelly Roll - Lonely Road (Official Music...,“Lonely Road” from mgk & Jelly Roll is availab...,2024-08-01T05:45:43.128Z,6 days ago,b6-JNeXxN3s,https://youtube.com/watch?v=b6-JNeXxN3s,mgk,UCUs8sGiP4avNaYNVO22INhQ,https://youtube.com/channel/UCUs8sGiP4avNaYNVO...,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",5682108,"5,682,108 views",289,4:49,True,False,False
1,YTB Fatt & Lil Durk - Conspiracy V2 (Official ...,"Stream ""On Zai"" Now: http://ytbfatt.lnk.to/onz...",2024-08-01T03:21:43.128Z,7 days ago,YbDzBpILqNY,https://youtube.com/watch?v=YbDzBpILqNY,YTB Fatt,UCqfqdCqPHxgtdJ0m32obDiw,https://youtube.com/channel/UCqfqdCqPHxgtdJ0m3...,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",2652067,"2,652,067 views",190,3:10,True,False,False
2,Lil Yachty & Ian - Hate Me (Official Music Video),Lyrical Lemonade Presents:\nLil Yachty & Ian -...,2024-08-01T05:45:43.128Z,6 days ago,FjFPy3N2tV4,https://youtube.com/watch?v=FjFPy3N2tV4,Lyrical Lemonade,UCtylTUUVIGY_i5afsQYeBZA,https://youtube.com/@lyricalemonade,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",4064274,"4,064,274 views",163,2:43,True,False,False
3,Post Malone ft. Luke Combs - Guy For That (Off...,Official “Guy For That” music video by Post Ma...,2024-08-01T05:45:43.128Z,6 days ago,b1aBzAE-IFY,https://youtube.com/watch?v=b1aBzAE-IFY,Post Malone,UCeLHszkByNZtPKcaVXOCOQQ,https://youtube.com/channel/UCeLHszkByNZtPKcaV...,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",4246819,"4,246,819 views",194,3:14,True,False,False
4,Lil Scoom89 - Blood In Blood Out (Official Mus...,Official Video for 'Blood In Blood Out'\nDedic...,2024-08-01T00:57:43.128Z,8 days ago,wBR3evySKDY,https://youtube.com/watch?v=wBR3evySKDY,Lil Scoom89,UCoUaFwRR-GHowgFXfkSS_7w,https://youtube.com/@LilScoom89,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",1394598,"1,394,598 views",163,2:43,False,False,False

In [81]:
# structure
print(df_music.columns)
print(df_music.shape)

Index(['title', 'description', 'publishedDate', 'publishedText', 'videoId',
       'videoUrl', 'channelName', 'channelId', 'channelUrl', 'thumbnails',
       'views', 'viewsText', 'duration', 'durationText', 'verified',
       'creatorOnRise', 'isShort'],
      dtype='object')
(930, 17)

In [82]:
# information
print(df_music.info())
print(df_music.describe())

# missing value
print(df_music.isna().sum())

# duplicate value
df_music.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          930 non-null    object
 1   description    926 non-null    object
 2   publishedDate  930 non-null    object
 3   publishedText  930 non-null    object
 4   videoId        930 non-null    object
 5   videoUrl       930 non-null    object
 6   channelName    930 non-null    object
 7   channelId      930 non-null    object
 8   channelUrl     930 non-null    object
 9   thumbnails     930 non-null    object
 10  views          930 non-null    int64
 11  viewsText      930 non-null    object
 12  duration       930 non-null    int64
 13  durationText   930 non-null    object
 14  verified       930 non-null    bool
 15  creatorOnRise  930 non-null    bool
 16  isShort        930 non-null    bool
dtypes: bool(3), int64(2), object(12)
memory usage: 104.6+ KB
None
              views    duration
count  9.300000e+02  930.000000
mean   5.452801e+06  194.792473
std    1.096697e+07   39.137787
min    3.964200e+04  113.000000
25%    7.395838e+05  164.000000
50%    1.845923e+06  192.000000
75%    4.561997e+06  220.000000
max    8.884766e+07  355.000000
title            0
description      4
publishedDate    0
publishedText    0
videoId          0
videoUrl         0
channelName      0
channelId        0
channelUrl       0
thumbnails       0
views            0
viewsText        0
duration         0
durationText     0
verified         0
creatorOnRise    0
isShort          0
dtype: int64

0

In [85]:
# view 4 missing description
mask = df_music["description"].isna()
df_music[mask]

,title,description,publishedDate,publishedText,videoId,videoUrl,channelName,channelId,channelUrl,thumbnails,views,viewsText,duration,durationText,verified,creatorOnRise,isShort
87,DeeBaby - Malibu Baby,NaN,2024-08-03T08:08:01.217Z,5 days ago,GkPBfvYJ2Ok,https://youtube.com/watch?v=GkPBfvYJ2Ok,Official DeeBabyTV,UC4Um_x-Py3W1WFdMmxACOmg,https://youtube.com/@officialdeebabytv4721,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",388012,"388,012 views",166,2:46,False,False,False
116,DeeBaby - Malibu Baby,NaN,2024-08-04T05:45:36.024Z,6 days ago,GkPBfvYJ2Ok,https://youtube.com/watch?v=GkPBfvYJ2Ok,Official DeeBabyTV,UC4Um_x-Py3W1WFdMmxACOmg,https://youtube.com/@officialdeebabytv4721,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",449459,"449,459 views",166,2:46,False,False,False
146,DeeBaby - Malibu Baby,NaN,2024-08-05T03:20:28.435Z,7 days ago,GkPBfvYJ2Ok,https://youtube.com/watch?v=GkPBfvYJ2Ok,Official DeeBabyTV,UC4Um_x-Py3W1WFdMmxACOmg,https://youtube.com/@officialdeebabytv4721,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",505105,"505,105 views",166,2:46,False,False,False
178,DeeBaby - Malibu Baby,NaN,2024-08-06T00:55:33.869Z,8 days ago,GkPBfvYJ2Ok,https://youtube.com/watch?v=GkPBfvYJ2Ok,Official DeeBabyTV,UC4Um_x-Py3W1WFdMmxACOmg,https://youtube.com/@officialdeebabytv4721,"[{'quality': 'maxres', 'url': 'https://i.ytimg...",564588,"564,588 views",166,2:46,False,False,False

In [89]:
# save as csv
#df_music.to_csv("data/music.csv", index=False)